# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/jammy64"
  #increase timeout
  config.vm.boot_timeout = 2000
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  
  # configure k8s basic setup
  config.vm.provision :shell, path: "../common/scripts/k8s-basic.sh"
end